---
title: "Readme"
author: "Necula Calin"
date: "02/21/2015"
output: html_document
---

###Getting and Cleaning Data
##Course Project

The goal is to prepare tidy data that can be used for later analysis. 

This repository contains: 

| 1) a tidy data set called `tidyData.txt`
| 2) a script for performing the analysis called `run_analysis.R`
| 3) a code book that describes the variables, the data, and any transformations or work that I performed to clean up the data called `CodeBook.md`.
                  

One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 
